<a href="https://colab.research.google.com/github/deviarati18/Vectorization-Techniques-sentimentAnalysis/blob/main/Vectorization_techniques_sentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import string
import re
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score,accuracy_score,roc_auc_score,confusion_matrix
from sklearn.linear_model import LogisticRegression

In [ ]:
data = pd.read_csv("sa_data.csv")
data.head()

text sentiment
0  RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1  RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2  RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3  RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive

In [ ]:
corpus=data['text'].tolist()

In [ ]:
corpus

['RT @NancyLeeGrahn: How did everyone feel about the Climate Change question last night? Exactly. #GOPDebate',
 "RT @ScottWalker: Didn't catch the full #GOPdebate last night. Here are some of Scott's best lines in 90 seconds. #Walker16 http://t.co/ZSfF…",
 'RT @TJMShow: No mention of Tamir Rice and the #GOPDebate was held in Cleveland? Wow.',
 "RT @RobGeorge: That Carly Fiorina is trending -- hours after HER debate -- above any of the men in just-completed #GOPdebate says she's on …",
 'RT @DanScavino: #GOPDebate w/ @realDonaldTrump delivered the highest ratings in the history of presidential debates. #Trump2016 http://t.co…',
 'RT @GregAbbott_TX: @TedCruz: "On my first day I will rescind every illegal executive action taken by Barack Obama." #GOPDebate @FoxNews',
 'RT @warriorwoman91: I liked her and was happy when I heard she was going to be the moderator. Not anymore. #GOPDebate @megynkelly  https://…',
 'Going on #MSNBC Live with @ThomasARoberts around 2 PM ET.  #GOPDebate',
 'Deer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer= CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['00', '000', '00pm', ..., 'zygote', 'zzcrane', '⁰capable'],
      dtype=object)

In [ ]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 1))

In [ ]:
X2 = vectorizer2.fit_transform(corpus)

In [ ]:
vectorizer2.get_feature_names_out()

array(['00', '000', '00pm', ..., 'zygote', 'zzcrane', '⁰capable'],
      dtype=object)

In [ ]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Decision Tree and logistic regression- word ngram(1,1)

DECISION TREE

In [ ]:
y = data["sentiment"]

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ypred2 = clf_gini.predict(X_test)
from sklearn.metrics import accuracy_score

In [ ]:
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ypred2)))


Model accuracy score with criterion gini index: 0.6047


LOGISTIC REGRESSION

In [ ]:
from sklearn.linear_model import LogisticRegression
LRM2 = LogisticRegression(random_state=0,max_iter=500)
LRM2.fit(X_train,y_train)
y_pred2 = LRM2.predict(X_test)
accuracy_score(y_pred2,y_test)

0.6864864864864865

# Decision Tree and logistic regression- word ngram(1,2)

DECISION TREE

In [ ]:
vectorizer3 = CountVectorizer(analyzer='word', ngram_range=(1, 2))
X3 = vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()


array(['00', '00 crowd', '00 edt', ..., 'zzcrane me', '⁰capable',
       '⁰capable fighting'], dtype=object)

In [ ]:
print(X3.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X3, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
y3 = clf_gini.predict(X_test)
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y3)))


Model accuracy score with criterion gini index: 0.6101


LOGISTIC REGRESSION

In [ ]:

LRM3 = LogisticRegression(random_state=0,max_iter=500)
LRM3.fit(X_train,y_train)
y_pred3 = LRM3.predict(X_test)
accuracy_score(y_pred3,y_test)

0.705945945945946

# DT and LR char-ngram(1,1)


In [ ]:
vectorizer4 = CountVectorizer(analyzer='char', ngram_range=(1, 1))
X4 = vectorizer4.fit_transform(corpus)
vectorizer4.get_feature_names_out()

array(['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+',
       ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', ':', ';', '=', '?', '@', '[', '\\', ']', '^', '_', '`', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|',
       '~', '\xa0', '¯', '·', '»', 'à', 'é', 'î', 'ā', 'ł', 'ə', 'ˈ', 'ˌ',
       'ٌ', '–', '—', '―', '‘', '’', '“', '”', '•', '…', '‼', '⁰', '↑',
       '→', '↓', '↔', '⇒', '▀', '█', '►', '◄', '☑', '☜', '☞', '☢', '♀',
       '⚡', '✅', '✋', '✔', '✯', '❤', '➡', '⬆', '⬇', '》', 'ツ', '・', '️',
       '�', '🇸', '🇺', '🌍', '🌷', '🍔', '🍷', '🍺', '🎀', '🎉', '🎤', '🎪', '🏻',
       '🏼', '🏽', '🏾', '🏿', '🐍', '🐘', '👀', '👉', '👊', '👋', '👌', '👍', '👎',
       '👏', '👑', '👓', '👨', '👭', '👴', '👶', '👸', '👺', '💀', '💁', '💛', '💢',
       '💣', '💥', '💧', '💨', '💩', '💪', '💰', '💸', '📢', '📲', '📷', '🔇', '🔥',
       '🔨', '🔪', '🔫', '🗽', '😀', '😁', '😂', '😄', '😆', '😉', '😊

In [ ]:
print(X4.toarray())

[[ 0 14  0 ...  0  0  0]
 [ 0 20  0 ...  0  0  0]
 [ 0 14  0 ...  0  0  0]
 ...
 [ 0 19  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0 11  2 ...  0  0  0]]


DT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X4, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
y4 = clf_gini.predict(X_test)
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y4)))

Model accuracy score with criterion gini index: 0.6086


LR

In [ ]:
from sklearn.linear_model import LogisticRegression
LRM4 = LogisticRegression(random_state=0,max_iter=900)
LRM4.fit(X_train,y_train)
y_pred4 = LRM4.predict(X_test)
accuracy_score(y_pred4,y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6263063063063063

# DT and LR  char-ngram(1,2)

In [ ]:
vectorizer5 = CountVectorizer(analyzer='char', ngram_range=(1, 2))
X5 = vectorizer5.fit_transform(corpus)
vectorizer5.get_feature_names_out()

array(['\n', '\n"', '\n#', ..., '\U000fe4e6 ', '\U000fe4ec',
       '\U000fe4ec\U000fe4e6'], dtype=object)

In [ ]:
print(X5.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X5, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
y5 = clf_gini.predict(X_test)
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y5)))

Model accuracy score with criterion gini index: 0.6141


LR

In [ ]:
from sklearn.linear_model import LogisticRegression
LRM5 = LogisticRegression(random_state=0,max_iter=800)
LRM5.fit(X_train,y_train)
y_pred5 = LRM5.predict(X_test)
accuracy_score(y_pred5,y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6533333333333333

# TF-IDF Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer0= TfidfVectorizer()
X = vectorizer0.fit_transform(corpus)
vectorizer0.get_feature_names_out()

array(['00', '000', '00pm', ..., 'zygote', 'zzcrane', '⁰capable'],
      dtype=object)

In [ ]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
vectorizer6 = TfidfVectorizer(analyzer='word', ngram_range=(1, 1))
X6 = vectorizer6.fit_transform(corpus)
vectorizer6.get_feature_names_out()

array(['00', '000', '00pm', ..., 'zygote', 'zzcrane', '⁰capable'],
      dtype=object)

In [ ]:
print(X6.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# DT and LR word ngram(1,1)

In [ ]:
y = data["sentiment"]

 DT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X6, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ypred6 = clf_gini.predict(X_test)

In [ ]:
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ypred6)))

Model accuracy score with criterion gini index: 0.6112


LR

In [ ]:
LRM6 = LogisticRegression(random_state=0,max_iter=800)
LRM6.fit(X_train,y_train)
y_pred6 = LRM6.predict(X_test)
accuracy_score(y_pred6,y_test)

0.7009009009009008

In [ ]:
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred6)))

Model accuracy score with criterion gini index: 0.7009


# DT-LR word ngram (1,2)

In [ ]:
vectorizer7 = TfidfVectorizer(analyzer='word', ngram_range=(1, 2))
X7 = vectorizer7.fit_transform(corpus)
vectorizer7.get_feature_names_out()

array(['00', '00 crowd', '00 edt', ..., 'zzcrane me', '⁰capable',
       '⁰capable fighting'], dtype=object)

In [ ]:
print(X7.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


DT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X7, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ypred7 = clf_gini.predict(X_test)
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ypred7)))

Model accuracy score with criterion gini index: 0.6105


LR

In [ ]:
LRM7 = LogisticRegression(random_state=0,max_iter=800)
LRM7.fit(X_train,y_train)
y_pred7 = LRM7.predict(X_test)
accuracy_score(y_pred7,y_test)

0.6962162162162162

# DT-LR char ngram (1,1)

In [ ]:
vectorizer8 = TfidfVectorizer(analyzer='char', ngram_range=(1, 1))
X8 = vectorizer8.fit_transform(corpus)
vectorizer8.get_feature_names_out()

array(['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+',
       ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', ':', ';', '=', '?', '@', '[', '\\', ']', '^', '_', '`', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|',
       '~', '\xa0', '¯', '·', '»', 'à', 'é', 'î', 'ā', 'ł', 'ə', 'ˈ', 'ˌ',
       'ٌ', '–', '—', '―', '‘', '’', '“', '”', '•', '…', '‼', '⁰', '↑',
       '→', '↓', '↔', '⇒', '▀', '█', '►', '◄', '☑', '☜', '☞', '☢', '♀',
       '⚡', '✅', '✋', '✔', '✯', '❤', '➡', '⬆', '⬇', '》', 'ツ', '・', '️',
       '�', '🇸', '🇺', '🌍', '🌷', '🍔', '🍷', '🍺', '🎀', '🎉', '🎤', '🎪', '🏻',
       '🏼', '🏽', '🏾', '🏿', '🐍', '🐘', '👀', '👉', '👊', '👋', '👌', '👍', '👎',
       '👏', '👑', '👓', '👨', '👭', '👴', '👶', '👸', '👺', '💀', '💁', '💛', '💢',
       '💣', '💥', '💧', '💨', '💩', '💪', '💰', '💸', '📢', '📲', '📷', '🔇', '🔥',
       '🔨', '🔪', '🔫', '🗽', '😀', '😁', '😂', '😄', '😆', '😉', '😊

In [ ]:
X8.shape


(13871, 217)

In [ ]:
print(X8.toarray())

[[0.         0.49473724 0.         ... 0.         0.         0.        ]
 [0.         0.54238977 0.         ... 0.         0.         0.        ]
 [0.         0.61009465 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.62146799 0.         ... 0.         0.         0.        ]
 [0.         0.59983725 0.         ... 0.         0.         0.        ]
 [0.         0.37425118 0.22127681 ... 0.         0.         0.        ]]


DT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X8, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ypred8 = clf_gini.predict(X_test)
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ypred8)))

Model accuracy score with criterion gini index: 0.6133


LR

In [ ]:
LRM8 = LogisticRegression(random_state=0,max_iter=800)
LRM8.fit(X_train,y_train)
y_pred8 = LRM8.predict(X_test)
accuracy_score(y_pred8,y_test)

0.6136936936936936

# DT and LR for char-ngram(1,2)

In [ ]:
vectorizer9 = TfidfVectorizer(analyzer='char', ngram_range=(1, 2))
X9 = vectorizer9.fit_transform(corpus)
vectorizer9.get_feature_names_out()

array(['\n', '\n"', '\n#', ..., '\U000fe4e6 ', '\U000fe4ec',
       '\U000fe4ec\U000fe4e6'], dtype=object)

In [ ]:
print(X9.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


DT

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X9, y, test_size=0.2, random_state=0)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ypred9 = clf_gini.predict(X_test)
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ypred9)))

Model accuracy score with criterion gini index: 0.6216


LR

In [ ]:
LRM9 = LogisticRegression(random_state=0,max_iter=800)
LRM9.fit(X_train,y_train)
y_pred9 = LRM9.predict(X_test)
accuracy_score(y_pred9,y_test)

0.6753153153153153

# WORD2VEC

In [ ]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import nltk
nltk.download('punkt')
import gensim
from gensim.models import Word2Vec

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
## tokenising into words

from nltk.tokenize import word_tokenize
data['text'].dropna(inplace=True)
data['text'] = data['text'].apply(word_tokenize)

In [ ]:
model = Word2Vec(sentences=data['text'], vector_size=150, window=5, min_count=1, sg=1)

In [ ]:
data['text']

0        [RT, @, NancyLeeGrahn, :, How, did, everyone, ...
1        [RT, @, ScottWalker, :, Did, n't, catch, the, ...
2        [RT, @, TJMShow, :, No, mention, of, Tamir, Ri...
3        [RT, @, RobGeorge, :, That, Carly, Fiorina, is...
4        [RT, @, DanScavino, :, #, GOPDebate, w/, @, re...
                               ...                        
13866    [RT, @, cappy_yarbrough, :, Love, to, see, men...
13867    [RT, @, georgehenryw, :, Who, thought, Huckabe...
13868    [RT, @, Lrihendry, :, #, TedCruz, As, Presiden...
13869    [RT, @, JRehling, :, #, GOPDebate, Donald, Tru...
13870    [RT, @, Lrihendry, :, #, TedCruz, headed, into...
Name: text, Length: 13871, dtype: object

In [ ]:
data['text']


0        [RT, @, NancyLeeGrahn, :, How, did, everyone, ...
1        [RT, @, ScottWalker, :, Did, n't, catch, the, ...
2        [RT, @, TJMShow, :, No, mention, of, Tamir, Ri...
3        [RT, @, RobGeorge, :, That, Carly, Fiorina, is...
4        [RT, @, DanScavino, :, #, GOPDebate, w/, @, re...
                               ...                        
13866    [RT, @, cappy_yarbrough, :, Love, to, see, men...
13867    [RT, @, georgehenryw, :, Who, thought, Huckabe...
13868    [RT, @, Lrihendry, :, #, TedCruz, As, Presiden...
13869    [RT, @, JRehling, :, #, GOPDebate, Donald, Tru...
13870    [RT, @, Lrihendry, :, #, TedCruz, headed, into...
Name: text, Length: 13871, dtype: object

In [ ]:
X = []
for text in data['text']:
    textvec = []
    for word in text:
        textvec.append(model.wv[word])
    X.append(np.mean(textvec))

In [ ]:
X

[0.013759801,
 0.010025873,
 0.011874985,
 0.01364155,
 0.007970831,
 0.008465814,
 0.014216332,
 0.005746793,
 0.0079997815,
 0.012075761,
 0.0038215392,
 0.012303859,
 0.015856443,
 0.013144856,
 0.013146608,
 0.011991396,
 0.005572956,
 0.0070782024,
 0.011538333,
 0.009074274,
 0.011242844,
 0.013332869,
 0.009005448,
 0.0036678025,
 0.0109736165,
 0.017377341,
 0.010070599,
 0.010839601,
 0.013246477,
 0.004949372,
 0.009529302,
 0.012454872,
 0.009800952,
 0.009482174,
 0.008676134,
 0.0053909365,
 0.0042999084,
 0.014848489,
 0.01063307,
 0.008536181,
 0.008998493,
 0.010296111,
 0.0018840358,
 0.011811306,
 0.009922556,
 0.012132511,
 0.014917219,
 0.007989521,
 0.007960437,
 0.0142895775,
 0.009365828,
 0.0068439017,
 0.009254166,
 0.0063694576,
 0.011090647,
 0.013037341,
 0.0140558025,
 0.0042868718,
 0.011933227,
 0.009706411,
 0.011491894,
 0.011321546,
 0.007465625,
 0.007884848,
 0.007869525,
 0.016169958,
 0.007170802,
 0.009147251,
 0.008031267,
 0.009186525,
 0.009897

DECISION TREE

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')


# fit the model
clf_gini.fit(X_train, y_train)
ywv = clf_gini.predict(X_test)
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, ywv)))

Model accuracy score with criterion gini index: 0.6245


LOGISTIC REGRESSION

In [ ]:

LRMwv = LogisticRegression(random_state=0,max_iter=500)
LRMwv.fit(X_train,y_train)
y_predwv = LRMwv.predict(X_test)
accuracy_score(y_predwv,y_test)

0.6547747747747747

GLOVE

In [ ]:
import numpy as np

In [ ]:
import gensim.downloader as api

glove_file = api.load("glove-twitter-50")

[================================================--] 96.2% 191.9/199.5MB downloaded


In [ ]:
data = pd.read_csv('sa_data.csv')
from nltk.tokenize import word_tokenize
data['text'].dropna(inplace=True)
data['text'] = data['text'].apply(word_tokenize)



In [ ]:
def text_to_vector(text):
    words = str(text).lower().split()
    vectors = np.zeros((len(words), 100))
    for i, word in enumerate(words):
        try:
            vectors[i] = glove_file[word]
        except KeyError:
            pass
    return np.mean(vectors, axis=0)





In [ ]:
data['vectors'] = data['text'].apply(text_to_vector)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data['vectors'], y, test_size=0.2, random_state=42)

Decision Tree

In [ ]:

clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0,max_features='sqrt')
clf_gini.fit(list(X_train), list(y_train))
y_glove = clf_gini.predict(list(X_test))
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_glove)))

Model accuracy score with criterion gini index: 0.6205


LOGICAL Regressor

In [ ]:
LRMgl = LogisticRegression(random_state=0,max_iter=500)
LRMgl.fit(list(X_train),list(y_train))
y_predgl = LRMgl.predict(list(X_test))
accuracy_score(y_predgl,list(y_test))

0.6205405405405405